### ISSUE TITLE
geomet.wkt.dumps fails with specific coordinates

### ISSUE THREAD

**Issue by victorsevero** [geomet/geomet#75] opened 2021-07-23 23:26 UTC
I found a bug (using [Hypothesis](https://github.com/HypothesisWorks/hypothesis)) with `geomet.wkt.dumps` when I try to round small values of coordinates with even smaller decimals. This is how you can reproduce this case:
```Python
import geomet

polygon = {'type': 'Polygon', 'coordinates': [[[0., 1.0000483598560095e-05]]]}
geomet.wkt.dumps(geometry, decimals=9)
```
which gives

> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/victor/.cache/pypoetry/virtualenvs/watermill-K62Kegsu-py3.9/lib/python3.9/site-packages/geomet/wkt.py", line 79, in dumps
    result = exporter(obj, decimals)
  File "/home/victor/.cache/pypoetry/virtualenvs/watermill-K62Kegsu-py3.9/lib/python3.9/site-packages/geomet/wkt.py", line 266, in _dump_polygon
    fmt = '(%s)' % ', '.join('(%s)' % r for r in rings)
  File "/home/victor/.cache/pypoetry/virtualenvs/watermill-K62Kegsu-py3.9/lib/python3.9/site-packages/geomet/wkt.py", line 266, in <genexpr>
    fmt = '(%s)' % ', '.join('(%s)' % r for r in rings)
  File "/home/victor/.cache/pypoetry/virtualenvs/watermill-K62Kegsu-py3.9/lib/python3.9/site-packages/geomet/wkt.py", line 262, in <genexpr>
    rings = (', '.join(' '.join(_round_and_pad(c, decimals)
  File "/home/victor/.cache/pypoetry/virtualenvs/watermill-K62Kegsu-py3.9/lib/python3.9/site-packages/geomet/wkt.py", line 262, in <genexpr>
    rings = (', '.join(' '.join(_round_and_pad(c, decimals)
  File "/home/victor/.cache/pypoetry/virtualenvs/watermill-K62Kegsu-py3.9/lib/python3.9/site-packages/geomet/wkt.py", line 262, in <genexpr>
    rings = (', '.join(' '.join(_round_and_pad(c, decimals)
  File "/home/victor/.cache/pypoetry/virtualenvs/watermill-K62Kegsu-py3.9/lib/python3.9/site-packages/geomet/wkt.py", line 199, in _round_and_pad
    rounded += '0' * (decimals - len(rounded.split('.')[1]))
IndexError: list index out of range

A curious thing I found is that greater values for `decimals` stops the error

**Comment by larsbutler** [comment] 2022-01-27 11:56
Hi @victorsevero, I'm unable to reproduce this.

```
$ python3.9
Python 3.9.8 (main, Nov 10 2021, 09:21:22) 
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from geomet import wkt
>>> polygon = {'type': 'Polygon', 'coordinates': [[[0., 1.0000483598560095e-05]]]}
>>> output = wkt.dumps(polygon, decimals=9)
>>> print(output)
POLYGON ((0.000000000 0.000010000))
>>> 
```

Could you please verify what input you're using to produce this error?

**Comment by larsbutler** [comment] 2022-10-22 10:36
This issue hasn't been updated in a while, and I'm unable to reproduce it. Closing for now.

**Closed by larsbutler** 2022-10-22 10:36 UTC
Labels: bug
